# Generated by Django 5.0.3 on 2024-05-02 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturesVendorsProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('vendor_code', models.CharField(unique=True)),
                ('name', models.CharField(max_length=1000)),
                ('contact_details', models.TextField()),
                ('address', models.TextField()),
                ('on_time_delivery_rate', models.FloatField()),
                ('quality_rating_avg', models.FloatField()),
                ('average_response_time', models.FloatField()),
                ('fulfillment_rate', models.FloatField()),
            ],
            options={
                'verbose_name': 'Vendor Profile Model',
                'verbose_name_plural': 'Vendor Profile Models',
            },
        ),
        migrations.CreateModel(
            name='FeaturesPurchaseOrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('po_number', models.CharField(unique=True)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('delivery_date', models.DateField()),
                ('items', models.JSONField()),
                ('quantity', models.IntegerField()),
                ('status', models.CharField()),
                ('quality_rating', models.FloatField(blank=True, null=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('acknowledgment_date', models.DateField(blank=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FeaturesPurchaseOrder_vendor', to='features.featuresvendorsprofilemodel')),
            ],
            options={
                'verbose_name': 'Purchase Order Model',
                'verbose_name_plural': 'Purchase Order Models',
            },
        ),
        migrations.CreateModel(
            name='FeaturesHistoricalPerformanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('on_time_delivery_rate', models.FloatField()),
                ('quality_rating_avg', models.FloatField()),
                ('average_response_time', models.FloatField()),
                ('fulfillment_rate', models.FloatField()),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FeaturesHistoricalPerformanceModel_vendor', to='features.featuresvendorsprofilemodel')),
            ],
            options={
                'verbose_name': 'Historical Performance Model',
                'verbose_name_plural': 'Historical Performance Models',
            },
        ),
    ]
