# Generated by Django 5.0.3 on 2024-05-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurespurchaseordermodel',
            name='acknowledgment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='featurespurchaseordermodel',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
