# Generated by Django 5.0.3 on 2024-05-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_alter_featurespurchaseordermodel_acknowledgment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurespurchaseordermodel',
            name='issue_date',
            field=models.DateTimeField(),
        ),
    ]
