# Generated by Django 5.0.3 on 2024-05-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_alter_featureshistoricalperformancemodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureshistoricalperformancemodel',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
